version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5600:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup/init-script/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_PORT}:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET}
    volumes:
      - minio_data:/data
  pr-core-agent:
    image: trucxinhlunglinh/pr-core-agent:1.0
    container_name: pr-core-agent
    ports:
      - "${AGENT_PORT}:5001"
    environment:
      - AGENT_HOST=${AGENT_HOST}
      - AGENT_PORT=${AGENT_PORT}
      - AGENT_SECRET=${AGENT_SECRET}

volumes:
  postgres_data:
  minio_data:
